name: Generate Databay showcase

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate snake animation
        uses: Platane/snk@v2.2.1
        with:
          github_user_name: Andrehlb
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Upload SVG
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: output
          FOLDER: dist
          REPOSITORY: Andrehlb/Andrehlb
