name: Generate Datas

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Generate Data
        uses: Platane/snk@master
        with:
          github_user_name: Andrehlb
          svg_out_path: dist/github-contribution-grid-snake.svg
          width: 100
          height: 100
